import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { api } from "~/utils/api";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Gul Hotel</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="overflow-hidden bg-gradient-to-b from-slate-950 to-teal-950">
        <div className="fixed w-screen">
          <div className="navbar">
            <div className="flex-1">
              <Image src={"/logo.png"} height={100} width={100} className="w-14 m-2" alt="logo"/>
            </div>
            <div className="flex-none">
            <ul className="menu uppercase menu-horizontal px-1">
              <li><a href="">Prices</a></li>
              <li><a href="">Contact</a></li>
            </ul>
            </div>
          </div>
        </div>
        <div className="page">
          <div className="flex flex-row">
            <div className="flex min-h-screen w-1/2 flex-col items-end justify-center bg-black/60 p-4">
              <h1 className="text-right tracking-wider border-b">Stay</h1>
              <p className="text-lg uppercase text-center font-lato font-light">without a <br /> <span className="font-black">dent</span>{" "}in your <br /> pocket</p>
            </div>
            <div className="flex flex-col min-h-screen gap-4 justify-center p-4">
              <button className="btn btn-primary">Book Now</button>
              <button className="btn btn-primary">Have A Tour</button>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
